# Generated by Django 4.0.6 on 2022-12-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usera',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='usera',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='usera',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
